set(src_dirs
            hardware/LED
            hardware/LED/LED_CC
            hardware/LED/LED_PC
            hardware/BEEP
            hardware/BEEP/BEEP_CC
            hardware/BEEP/BEEP_PC
            hardware/ADC
            hardware/ADC/ADC_CC
            hardware/ADC/ADC_PC
            hardware/ENCODER
            hardware/ENCODER/ENCODER_CC
            hardware/ENCODER/ENCODER_PC
            hardware/PID
            hardware/IMU
            hardware/IMU/IMU_CC
            hardware/IMU/IMU_PC
            hardware/TIMER
            hardware/TIMER/TIMER_CC
            hardware/TIMER/TIMER_PC
            hardware/Driver/UART
            hardware/Driver/UART/UART_CC
            hardware/Driver/UART/UART_PC
            hardware/WIFI
            hardware/WIFI/WIFI_CC
            hardware/WIFI/WIFI_PC
            hardware/Bluetooth
            hardware/Bluetooth/Bluetooth_CC
            hardware/Bluetooth/Bluetooth_PC
            hardware/Driver/I2C
            hardware/Driver/I2C/I2C_CC
            hardware/Driver/I2C/I2C_PC
            hardware/LIDAR
            hardware/LIDAR/LIDAR_CC
            hardware/LIDAR/LIDAR_PC
            hardware/PWM
            hardware/PWM/PWM_CC
            hardware/PWM/PWM_PC
            hardware/SERVO
            hardware/SERVO/SERVO_CC
            hardware/SERVO/SERVO_PC
            hardware/BOARD
            App/App_Init
            App/App_Publisher_Imu
            App/App_Publisher_LaserScan
            App/App_Publisher_Odom
            App/App_Publisher_ServoState
            App/App_Subscriber_Servo
            App/App_Subscriber_Twist
            App/App_Bluetooth
            Task/Task_Init
            Task/Task_IMU
            Task/Task_Lidar
            Task/Task_MotionControl
            Task/Task_ServoControl
            Task/Task_Odometry
            Task/Task_LedControl
            Task/Task_BeepControl)

set(include_dirs
            hardware
            hardware/LED
            hardware/LED/LED_CC
            hardware/LED/LED_PC
            hardware/BEEP
            hardware/BEEP/BEEP_CC
            hardware/BEEP/BEEP_PC
            hardware/ADC
            hardware/ADC/ADC_CC
            hardware/ADC/ADC_PC
            hardware/ENCODER
            hardware/ENCODER/ENCODER_CC
            hardware/ENCODER/ENCODER_PC
            hardware/PID
            hardware/IMU
            hardware/IMU/IMU_CC
            hardware/IMU/IMU_PC
            hardware/TIMER
            hardware/TIMER/TIMER_CC
            hardware/TIMER/TIMER_PC
            hardware/Driver/UART
            hardware/Driver/UART/UART_CC
            hardware/Driver/UART/UART_PC
            hardware/WIFI
            hardware/WIFI/WIFI_CC
            hardware/WIFI/WIFI_PC
            hardware/Bluetooth
            hardware/Bluetooth/Bluetooth_CC
            hardware/Bluetooth/Bluetooth_PC
            hardware/Driver/I2C
            hardware/Driver/I2C/I2C_CC
            hardware/Driver/I2C/I2C_PC
            hardware/LIDAR
            hardware/LIDAR/LIDAR_CC
            hardware/LIDAR/LIDAR_PC
            hardware/PWM
            hardware/PWM/PWM_CC
            hardware/PWM/PWM_PC
            hardware/SERVO
            hardware/SERVO/SERVO_CC
            hardware/SERVO/SERVO_PC
            hardware/BOARD
            APP
            App/App_Init
            App/App_Publisher_Imu
            App/App_Publisher_LaserScan
            App/App_Publisher_Odom
            App/App_Publisher_ServoState
            App/App_Subscriber_Servo
            App/App_Subscriber_Twist
            App/App_Bluetooth
            Task/Task_Init
            Task/Task_IMU
            Task/Task_Lidar
            Task/Task_MotionControl
            Task/Task_ServoControl
            Task/Task_Odometry
            Task/Task_LedControl
            Task/Task_BeepControl)

set(requires
            driver
            esp_adc
            esp_event
            esp_netif
            esp_wifi
            bt
            nvs_flash
            micro_ros_espidf_component)

idf_component_register(SRC_DIRS ${src_dirs} INCLUDE_DIRS ${include_dirs} REQUIRES ${requires})
component_compile_options(-ffast-math -O3 -Wno-error=format -Wno-format)
